name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          pull: true
          tags: |
            cezarique/sitepersonal:latest
          cache-from: type=registry,ref=cezarique/sitepersonal:cache
          cache-to: type=registry,ref=cezarique/sitepersonal:cache,mode=max
          
      - name: Trigger Coolify deploy
        env:
          COOLIFY_URL: ${{ secrets.COOLIFY_DOMAIN }}    # ex: http://89.41.182.64:8000 sau https://coolify.turliucezar.duckdns.org
          COOLIFY_UUID: ${{ secrets.COOLIFY_UUID }}
          COOLIFY_TOKEN: ${{ secrets.COOLIFY_TOKEN }}
        run: |
          curl -sSf -X POST "$COOLIFY_URL/api/v1/deploy" \
            -H "Authorization: Bearer $COOLIFY_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"uuid\":\"$COOLIFY_UUID\",\"force\":true}"



